# As variaveis foram comentadas para n√£o dar conflito com as variaveis de ambiente definidas no pytest.ini
# pyproject.toml
#[tool.pytest_env]
#PASTA_RECEBIMENTO="received"
#PASTA_PROCESSO="process"
#PASTA_PROCESSADO="processed"